# Generated by Django 3.0.8 on 2020-08-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0002_auto_20200806_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramprofile',
            name='external_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='ID user in tg'),
        ),
    ]
