# Generated by Django 3.0.8 on 2020-07-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
